export const data = [
  {
    "_id": "66b4f8c6e6a2c31a4f000001",
    "nome": "Cafeína",
    "nomeIupac": "1,3,7-trimetilpurina-2,6-diona",
    "familia": "Alcaloides",
    "especie": "Coffea arabica",
    "smile": "Cn1cnc2c1c(=O)n(c(=O)n2C)C",
    "hba": 4,
    "hbd": 0,
    "massaMolecular": 194.19,
    "logP": -0.07,
    "atividadeBiologica": "Estimulante do sistema nervoso central"
  },
  {
    "_id": "66b4f8c6e6a2c31a4f000002",
    "nome": "Quercetina",
    "nomeIupac": "3,3′,4′,5,7-pentahidroxiflavona",
    "familia": "Flavonoides",
    "especie": "Allium cepa",
    "smile": "C1=CC(=C(C=C1C2=C(C(=O)C3=CC(=C(C=C3O2)O)O)O)O)O",
    "hba": 7,
    "hbd": 5,
    "massaMolecular": 302.24,
    "logP": 1.82,
    "atividadeBiologica": "Antioxidante e anti-inflamatório"
  },
  {
    "_id": "66b4f8c6e6a2c31a4f000003",
    "nome": "Resveratrol",
    "nomeIupac": "5-[(E)-2-(4-hidroxifenil)etenil]-1,3-benzenodiol",
    "familia": "Polifenóis",
    "especie": "Vitis vinifera",
    "smile": "C1=CC(=CC=C1/C=C/C2=CC(=C(C=C2)O)O)O",
    "hba": 3,
    "hbd": 3,
    "massaMolecular": 228.24,
    "logP": 3.1,
    "atividadeBiologica": "Antioxidante e cardioprotetor"
  },
  {
    "_id": "66b4f8c6e6a2c31a4f000004",
    "nome": "Curcumina",
    "nomeIupac": "(1E,6E)-1,7-bis(4-hidroxi-3-metoxifenil)-1,6-heptadieno-3,5-diona",
    "familia": "Polifenóis",
    "especie": "Curcuma longa",
    "smile": "COC1=CC(=C(C=C1O)/C=C/C(=O)C/C=C/C2=CC(=C(C=C2O)OC))",
    "hba": 6,
    "hbd": 2,
    "massaMolecular": 368.39,
    "logP": 3.29,
    "atividadeBiologica": "Anti-inflamatório e antioxidante"
  },
  {
    "_id": "66b4f8c6e6a2c31a4f000005",
    "nome": "Luteolina",
    "nomeIupac": "3′,4′,5,7-tetrahidroxiflavona",
    "familia": "Flavonoides",
    "especie": "Capsicum annuum",
    "smile": "C1=CC(=C(C=C1C2=C(C(=O)C3=CC(=C(C=C3O2)O)O)O)O)O",
    "hba": 6,
    "hbd": 4,
    "massaMolecular": 286.24,
    "logP": 2.06,
    "atividadeBiologica": "Antioxidante e modulador enzimático"
  },
  {
    "_id": "66b4f8c6e6a2c31a4f000006",
    "nome": "Capsaicina",
    "nomeIupac": "(E)-N-(4-hidroxi-3-metoxibenzil)-8-metil-6-nonenamida",
    "familia": "Capsaicinoides",
    "especie": "Capsicum frutescens",
    "smile": "CC(C)=CCCCC/C=C/C(=O)NC1=CC(=C(C=C1O)OC)C",
    "hba": 3,
    "hbd": 2,
    "massaMolecular": 305.41,
    "logP": 3.92,
    "atividadeBiologica": "Analgésico tópico e irritante"
  },
  {
    "_id": "66b4f8c6e6a2c31a4f000007",
    "nome": "Apigenina",
    "nomeIupac": "4′,5,7-trihidroxiflavona",
    "familia": "Flavonoides",
    "especie": "Petroselinum crispum",
    "smile": "C1=CC(=C(C=C1C2=C(C(=O)C3=CC(=C(C=C3O2)O)O)O)O)O",
    "hba": 5,
    "hbd": 3,
    "massaMolecular": 270.24,
    "logP": 2.46,
    "atividadeBiologica": "Antioxidante e anti-inflamatório"
  },
  {
    "_id": "66b4f8c6e6a2c31a4f000008",
    "nome": "Genisteína",
    "nomeIupac": "4′,5,7-trihidroxiisoflavona",
    "familia": "Isoflavonoides",
    "especie": "Glycine max",
    "smile": "C1=CC(=C(C=C1C2=C(C(=O)C3=CC(=C(C=C3O2)O)O)O)O)O",
    "hba": 5,
    "hbd": 3,
    "massaMolecular": 270.24,
    "logP": 2.27,
    "atividadeBiologica": "Estrogênico e antioxidante"
  },
  {
    "_id": "66b4f8c6e6a2c31a4f000009",
    "nome": "Epicatequina",
    "nomeIupac": "(2R,3R)-2-(3,4-dihidroxifenil)-3,4-diidro-2H-cromen-3,5,7-triol",
    "familia": "Flavanóis",
    "especie": "Camellia sinensis",
    "smile": "C1C(C(OC2=CC(=C(C=C21)O)O)C3=CC(=C(C=C3)O)O)O",
    "hba": 6,
    "hbd": 5,
    "massaMolecular": 290.27,
    "logP": 1.37,
    "atividadeBiologica": "Antioxidante e cardioprotetor"
  },
  {
    "_id": "66b4f8c6e6a2c31a4f00000a",
    "nome": "Rutina",
    "nomeIupac": "5,7-dihidroxi-2-(3,4-dihidroxifenil)-4H-1-benzopiran-4-ona-3-O-rutinosídeo",
    "familia": "Flavonoides glicosilados",
    "especie": "Fagopyrum esculentum",
    "smile": "C1=CC(=C(C=C1C2=C(C(=O)C3=CC(=C(C=C3O2)O)O)OC4C(C(C(C(O4)CO)O)O)O)O)O",
    "hba": 15,
    "hbd": 10,
    "massaMolecular": 610.52,
    "logP": -1.13,
    "atividadeBiologica": "Antioxidante e vasoprotetor"
  }
]
